/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./pages/**/*.{js,ts,jsx,tsx,mdx}", "./components/**/*.{js,ts,jsx,tsx,mdx}", "./app/**/*.{js,ts,jsx,tsx,mdx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        brutal: {
          primary: "#000000",
          secondary: "#ffffff",
          accent: "#ff0000",
          warning: "#ffff00",
          success: "#00ff00",
          error: "#ff0000",
          gray: "#808080",
          darkgray: "#404040",
          lightgray: "#c0c0c0",
          blue: "#0000ff",
          magenta: "#ff00ff",
          cyan: "#00ffff",
        },
      },
      fontFamily: {
        mono: ["Courier New", "monospace"],
        serif: ["Times New Roman", "serif"],
        sans: ["Arial", "Helvetica", "sans-serif"],
        display: ["Impact", "Arial Black", "sans-serif"],
      },
      fontSize: {
        xs: "10px",
        sm: "12px",
        base: "14px",
        lg: "16px",
        xl: "20px",
        "2xl": "24px",
        "3xl": "30px",
        "4xl": "36px",
        "5xl": "48px",
        "6xl": "60px",
        "7xl": "72px",
        "8xl": "96px",
        "9xl": "128px",
        brutal: "200px",
      },
      spacing: {
        0: "0px",
        1: "4px",
        2: "8px",
        3: "12px",
        4: "16px",
        5: "20px",
        6: "24px",
        8: "32px",
        10: "40px",
        12: "48px",
        16: "64px",
        20: "80px",
        24: "96px",
        32: "128px",
        40: "160px",
        48: "192px",
        56: "224px",
        64: "256px",
        72: "288px",
        80: "320px",
        96: "384px",
      },
      borderWidth: {
        0: "0px",
        1: "1px",
        2: "2px",
        3: "3px",
        4: "4px",
        5: "5px",
        6: "6px",
        8: "8px",
        10: "10px",
        12: "12px",
        16: "16px",
        20: "20px",
      },
      animation: {
        blink: "blink 1s linear infinite",
        shake: "shake 0.5s ease-in-out infinite",
        "pulse-brutal": "pulse-brutal 2s cubic-bezier(0.4, 0, 0.6, 1) infinite",
        "bounce-brutal": "bounce-brutal 1s infinite",
        "spin-brutal": "spin-brutal 1s linear infinite",
      },
      keyframes: {
        blink: {
          "0%, 50%": { opacity: "1" },
          "51%, 100%": { opacity: "0" },
        },
        shake: {
          "0%, 100%": { transform: "translateX(0)" },
          "10%, 30%, 50%, 70%, 90%": { transform: "translateX(-2px)" },
          "20%, 40%, 60%, 80%": { transform: "translateX(2px)" },
        },
        "pulse-brutal": {
          "0%, 100%": {
            opacity: "1",
            transform: "scale(1)",
          },
          "50%": {
            opacity: "0.5",
            transform: "scale(1.05)",
          },
        },
        "bounce-brutal": {
          "0%, 20%, 53%, 80%, 100%": {
            transform: "translate3d(0,0,0)",
          },
          "40%, 43%": {
            transform: "translate3d(0, -20px, 0)",
          },
          "70%": {
            transform: "translate3d(0, -10px, 0)",
          },
          "90%": {
            transform: "translate3d(0, -4px, 0)",
          },
        },
        "spin-brutal": {
          "0%": { transform: "rotate(0deg)" },
          "100%": { transform: "rotate(360deg)" },
        },
      },
      boxShadow: {
        brutal: "8px 8px 0px 0px #000000",
        "brutal-hover": "12px 12px 0px 0px #000000",
        "brutal-inset": "inset 4px 4px 0px 0px #000000",
        "brutal-red": "8px 8px 0px 0px #ff0000",
        "brutal-blue": "8px 8px 0px 0px #0000ff",
        "brutal-yellow": "8px 8px 0px 0px #ffff00",
      },
      dropShadow: {
        brutal: "4px 4px 0px #000000",
        "brutal-red": "4px 4px 0px #ff0000",
        "brutal-blue": "4px 4px 0px #0000ff",
      },
    },
  },
  plugins: [],
};
